int str_tamanho (char*);
void str_copia (char*, char*);
void str_concatena (char*, char*);
char *unidade(int);
char *dezena(int);
char *centena(int);
void retorna_numero_extenso(char*, int);
int unidade_extensa(char*);
int dezena_extensa(char*);
int centena_extensa(char*);
